import { CROP_ASPECT, getCenterCroppedImageFile, loadImage } from "@/lib/cards/cropImage";

// Browser-only, OpenCV-backed perspective correction — only ever imported
// from a "use client" component (components/inventory/ScanAddTab.tsx).
// @techstark/opencv-js builds to a ~25MB chunk (~4MB over the wire), so it's
// always dynamically imported (never a top-level import) so webpack
// code-splits it into its own chunk — it never touches the main app bundle or
// PWA precache. See warmUpAutoCrop() below for when that chunk is fetched.
//
// OpenCV.js's TypeScript declarations (generated by `mirada`) are known to
// lag the actual runtime API (see the package's own README), so `cv` and the
// Mat values below are deliberately untyped rather than fought against
// incomplete/incorrect .d.ts coverage.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type CV = any;

interface Point {
  x: number;
  y: number;
}

let cvPromise: Promise<CV> | null = null;

// Mirrors the readiness pattern from @techstark/opencv-js's own README.
function loadCv(): Promise<CV> {
  if (!cvPromise) {
    cvPromise = import("@techstark/opencv-js").then(async (mod) => {
      let cv = (mod as { default?: CV }).default ?? mod;
      if (cv instanceof Promise) cv = await cv;
      if (!cv.Mat) {
        await new Promise<void>((resolve) => {
          cv.onRuntimeInitialized = () => resolve();
        });
      }
      return cv;
    });
  }
  return cvPromise;
}

// Starts fetching + initialising OpenCV without waiting for it. Call this the
// moment the scanner UI appears, NOT when the photo arrives: the chunk is ~4MB
// over the wire, which on a phone is tens of seconds, and getAutoCroppedImageFile
// can't start until it lands. Fetching it while the user is still framing and
// taking the shot hides that download behind time they were spending anyway.
//
// Safe to call repeatedly and safe to ignore — loadCv() memoises the in-flight
// promise, so this and the later await in getAutoCroppedImageFile share one
// fetch, and a failure here is swallowed (the real call re-awaits the same
// rejected promise and falls back to a center crop, exactly as before).
export function warmUpAutoCrop(): void {
  void loadCv().catch(() => {});
}

function distance(a: Point, b: Point): number {
  return Math.hypot(a.x - b.x, a.y - b.y);
}

// Standard "sum/diff" corner ordering (top-left has the smallest x+y,
// bottom-right the largest; top-right has the largest x-y, bottom-left the
// smallest) — the common technique for turning 4 unordered quad corners from
// a contour into a consistent TL/TR/BR/BL order for a perspective warp.
function orderCorners(points: Point[]): [Point, Point, Point, Point] {
  const sums = points.map((p) => p.x + p.y);
  const diffs = points.map((p) => p.x - p.y);
  return [
    points[sums.indexOf(Math.min(...sums))],
    points[diffs.indexOf(Math.max(...diffs))],
    points[sums.indexOf(Math.max(...sums))],
    points[diffs.indexOf(Math.min(...diffs))],
  ];
}

// cv.minAreaRect() returns {center: {x,y}, size: {width,height}, angle} (an
// embind conversion of cv::RotatedRect) — computed here rather than via
// cv.boxPoints (whose exact binding shape is unverified for this build) so
// this has no dependency beyond minAreaRect's well-documented return shape.
function rotatedRectToCorners(rect: { center: Point; size: { width: number; height: number }; angle: number }): Point[] {
  const theta = (rect.angle * Math.PI) / 180;
  const cos = Math.cos(theta);
  const sin = Math.sin(theta);
  const halfW = rect.size.width / 2;
  const halfH = rect.size.height / 2;
  return [
    { x: -halfW, y: -halfH },
    { x: halfW, y: -halfH },
    { x: halfW, y: halfH },
    { x: -halfW, y: halfH },
  ].map((o) => ({
    x: rect.center.x + o.x * cos - o.y * sin,
    y: rect.center.y + o.x * sin + o.y * cos,
  }));
}

// Finds the largest contour that plausibly is the photographed card and
// returns its four corners via a rotated bounding rectangle. Deliberately
// does NOT require the contour to approximate to an exact 4-vertex polygon —
// physical trading cards have rounded corners, which routinely make a strict
// polygon approximation produce 5+ vertices and get rejected, even though
// the contour is clearly a card. minAreaRect fits a rotated rectangle around
// the contour regardless of its exact vertex count, which handles rounded
// corners (and general contour noise) far more reliably. Returns null —
// never throws — when nothing confident is found, so the caller can fall
// back to a plain center crop.
function detectCardCorners(cv: CV, image: HTMLImageElement): [Point, Point, Point, Point] | null {
  const src = cv.imread(image);
  const gray = new cv.Mat();
  const blurred = new cv.Mat();
  const edged = new cv.Mat();
  const kernel = cv.Mat.ones(3, 3, cv.CV_8U);
  const contours = new cv.MatVector();
  const hierarchy = new cv.Mat();
  let bestContour: CV | null = null;

  try {
    cv.cvtColor(src, gray, cv.COLOR_RGBA2GRAY);
    cv.GaussianBlur(gray, blurred, new cv.Size(5, 5), 0);
    cv.Canny(blurred, edged, 50, 150);
    cv.dilate(edged, edged, kernel);
    cv.findContours(edged, contours, hierarchy, cv.RETR_LIST, cv.CHAIN_APPROX_SIMPLE);

    const imageArea = src.rows * src.cols;
    let bestArea = 0;

    for (let i = 0; i < contours.size(); i++) {
      const contour = contours.get(i);
      const area = cv.contourArea(contour);
      // A real card fills most of a close-up photo but rarely the whole
      // frame — that usually means we traced the photo's own border.
      if (area > imageArea * 0.15 && area < imageArea * 0.98 && area > bestArea) {
        bestArea = area;
        bestContour?.delete();
        bestContour = contour;
      } else {
        contour.delete();
      }
    }

    if (!bestContour) return null;
    const rotatedRect = cv.minAreaRect(bestContour);
    return orderCorners(rotatedRectToCorners(rotatedRect)) as [Point, Point, Point, Point];
  } finally {
    bestContour?.delete();
    src.delete();
    gray.delete();
    blurred.delete();
    edged.delete();
    kernel.delete();
    contours.delete();
    hierarchy.delete();
  }
}

// Output size follows the detected quad's own scale (capped to a sane range)
// rather than a fixed resolution, so a tight close-up isn't needlessly
// upscaled and a huge photo isn't kept needlessly huge — width is then
// forced to CROP_ASPECT regardless of the quad's exact (imperfect) shape.
function computeOutputSize(corners: [Point, Point, Point, Point]) {
  const [tl, tr, br, bl] = corners;
  const detectedWidth = Math.max(distance(tl, tr), distance(bl, br));
  const width = Math.min(Math.max(Math.round(detectedWidth), 300), 1000);
  const height = Math.round(width / CROP_ASPECT);
  return { width, height };
}

function warpToRect(
  cv: CV,
  image: HTMLImageElement,
  corners: [Point, Point, Point, Point],
  outWidth: number,
  outHeight: number
): HTMLCanvasElement {
  const src = cv.imread(image);
  const [tl, tr, br, bl] = corners;
  const srcTri = cv.matFromArray(4, 1, cv.CV_32FC2, [tl.x, tl.y, tr.x, tr.y, br.x, br.y, bl.x, bl.y]);
  const dstTri = cv.matFromArray(4, 1, cv.CV_32FC2, [0, 0, outWidth, 0, outWidth, outHeight, 0, outHeight]);
  const transform = cv.getPerspectiveTransform(srcTri, dstTri);
  const dst = new cv.Mat();

  try {
    cv.warpPerspective(
      src,
      dst,
      transform,
      new cv.Size(outWidth, outHeight),
      cv.INTER_LINEAR,
      cv.BORDER_CONSTANT,
      new cv.Scalar()
    );
    const canvas = document.createElement("canvas");
    canvas.width = outWidth;
    canvas.height = outHeight;
    cv.imshow(canvas, dst);
    return canvas;
  } finally {
    src.delete();
    srcTri.delete();
    dstTri.delete();
    transform.delete();
    dst.delete();
  }
}

function canvasToBlob(canvas: HTMLCanvasElement): Promise<Blob> {
  return new Promise((resolve, reject) => {
    canvas.toBlob(
      (blob) => (blob ? resolve(blob) : reject(new Error("Could not export cropped image."))),
      "image/jpeg",
      0.92
    );
  });
}

// Detects the photographed card's four corners (however skewed by camera
// angle) and perspective-warps them flat into a clean CROP_ASPECT rectangle.
// Falls back to a plain center crop — silently, no user-facing error — when
// no confident quad is found (low contrast, glare off a foil card, OpenCV
// failing to load) or the warp itself fails, since this must never block
// adding the card.
export async function getAutoCroppedImageFile(file: File, fileName: string): Promise<File> {
  try {
    const objectUrl = URL.createObjectURL(file);
    const image = await loadImage(objectUrl).finally(() => URL.revokeObjectURL(objectUrl));

    const cv = await loadCv();
    const corners = detectCardCorners(cv, image);
    if (!corners) return getCenterCroppedImageFile(file, fileName);

    const { width, height } = computeOutputSize(corners);
    const canvas = warpToRect(cv, image, corners, width, height);
    const blob = await canvasToBlob(canvas);
    return new File([blob], fileName, { type: "image/jpeg" });
  } catch (err) {
    console.error("getAutoCroppedImageFile: perspective crop failed, falling back to center crop", err);
    return getCenterCroppedImageFile(file, fileName);
  }
}
